# tries to analyse the edge expression levels (how specific edges are)
# based on the data generated by pappi/sql/edge_expression.sql
# Author: flick
###############################################################################

# load utils
source("utils.R", chdir=TRUE)

# load sql config and get connection
source("sql_config.R", chdir=TRUE)
con <- get_sql_conn()


# get data
data <- dbGetQuery(con, "
SELECT * FROM ppi_edge_expr
ORDER BY ExpressedFraction")

dbDisconnect(con)

plot(density(data$ExpressedFraction))

h <- hist(data$ExpressedFraction, breaks=100, plot=FALSE)
h$counts <- cumsum(h$counts)
h$density <- cumsum(h$density)
plot(h, col=rep(c("orange","lightblue"), each=50))

