# tries to analyse the edge expression levels (how specific edges are)
# based on the data generated by pappi/sql/edge_expression.sql
# Author: flick
###############################################################################

# load utils
source("utils.R", chdir=TRUE)

# load sql config and get connection
source("sql_config.R", chdir=TRUE)


# connect to the backup sqlite DB
con <- get_sql_conn("edge_expr.sqlite")

# get the real edge_expression
edge_expr_data <- dbGetQuery(con, "
	SELECT * FROM ppi_edge_expr
	ORDER BY ExpressedFraction")

batch_expr_data <- dbGetQuery(con,"
	SELECT * FROM edge_expr_rand_perm_results
	ORDER BY Experiment, Results ASC
	")

dbDisconnect(con)

real_expr_data <- edge_expr_data$ExpressedFraction


NUM_BREAKS <- 10

hist_breaks <- 0:NUM_BREAKS/NUM_BREAKS
#hist_breaks <- c(0,0.18,0.72,1)

h_real <- hist(real_expr_data, breaks=hist_breaks, plot=FALSE)
h_real_frac <- h_real$counts/sum(h_real$counts)

batch_results_matrix <- matrix(nrow=0, ncol=length(hist_breaks)-1)
for (i in unique(batch_expr_data$Experiment))
{
	values <- batch_expr_data$Results[which(batch_expr_data$Experiment == i)]
	h_batch_values <- hist(values, breaks=hist_breaks, plot=FALSE)
	h_batch_frac <- h_batch_values$counts/sum(h_batch_values$counts)
	batch_results_matrix <- rbind(batch_results_matrix, h_batch_frac)
}

matrix_mean <- apply(batch_results_matrix,2,mean)
matrix_sd <- apply(batch_results_matrix,2,sd)
matrix_ci <- 1.96*matrix_sd


fig = ggplot(xlim=c(0,1))
fig = fig + geom_bar(data=data.frame(x=h_real$mids, y=h_real_frac), aes(x=x,y=y, fill="Actual Data"),stat="identity")

fig = fig + geom_errorbar(data=data.frame(x=h_real$mids, mean=matrix_mean,ci=matrix_ci), aes(x=x, ymin=mean-ci, ymax=mean+ci, fill="Random Permutations"))
fig = fig + geom_point(data=data.frame(x=h_real$mids, mean=matrix_mean), aes(x=x, y=mean, fill="Random Permutations"))

fig = fig + scale_fill_manual(name="Edge Expression for:",values=c("orange","blue"))
fig


##fig = fig + stat_bin(data=as.data.frame(edge_expr_frac_rand), binwidth=binwidth, fill="blue", alpha=0.5, aes(x=edge_expr_frac_rand, y=5*..count../sum(..count..)), position="identity")
##fig = fig + stat_bin(data=as.data.frame(edge_expr_frac_glob_rand), binwidth=binwidth, alpha=0.5, aes(x=edge_expr_frac_glob_rand, y=5*..count../sum(..count..), fill="Random Permutations"), position="identity")
#fig = fig + stat_bin(data=edge_expr_data, binwidth=binwidth, alpha=0.5, aes(x=ExpressedFraction, y=5*..count../sum(..count..), fill="Actual Data"), position="identity")
#fig = fig + ylab("Fraction")
#fig = fig + xlab("Edge Expression")
#fig = fig + labs(title="Histogram of Edge Expression")
#fig = fig + scale_fill_manual(name="Edge Expression for:",values=c("orange","blue"))
#fig = fig + theme(legend.position=c(1,1),legend.justification=c(1,1))
##actually plot:
#fig







