# tries to analyse the edge expression levels (how specific edges are)
# based on the data generated by pappi/sql/edge_expression.sql
# Author: flick
###############################################################################

# load utils
source("utils.R", chdir=TRUE)

# load sql config and get connection
source("sql_config.R", chdir=TRUE)
con <- get_sql_conn()


rand_edge_expr_frac <- function(con, iterations=1, per_gene_permute=FALSE)
{

	# initiate empty result
	result <- c()
	
	# iterate random permutations and edge expression calculation
	for (i in 1:iterations)
	{
		# get tissue/cell.type expression data
		expr_data <- dbGetQuery(con, "
			SELECT * FROM hpa_tissue_expr
			ORDER BY Gene")
		
		if (per_gene_permute)
		{
			for (gene in unique(expr_data$Gene))
			{
				expr_data[which(expr_data$Gene == gene),"Expressed"] <- sample(expr_data[which(expr_data$Gene == gene),"Expressed"])
			}
		}
		else
		{
			# permutate expression
			expr_data$Expressed <- sample(expr_data$Expressed)
			# write new table
			dbWriteTable(con, "hpa_tissue_expr_rand", expr_data, overwrite=TRUE)
		}
		
		# intersect with edges to get edge-expression
		dbSendQuery(con, "DROP TABLE IF EXISTS ppi_edge_expr_rand")
		dbSendQuery(con, "
		CREATE TABLE ppi_edge_expr_rand AS
		SELECT
			a.Gene1,
			a.Gene2,
			SUM(CASE
				WHEN
					b.Expressed = 1 
					AND c.Expressed = 1
				THEN 1 
				ELSE 0 
				END) AS ExpressedCount,
			count() AS TotalCount
		FROM ppi_genes AS a
		INNER JOIN hpa_tissue_expr_rand AS b
			ON a.Gene1 = b.Gene
		INNER JOIN hpa_tissue_expr_rand AS c
			ON a.Gene2 = c.Gene
			AND b.Tissue = c.Tissue
			AND b.[Cell_Type] = c.[Cell_Type]
		GROUP BY
			a.Gene1, a.Gene2
		")
		
		dbSendQuery(con, "ALTER TABLE ppi_edge_expr_rand ADD ExpressedFraction float")
		dbSendQuery(con, "UPDATE ppi_edge_expr_rand
		SET ExpressedFraction = ExpressedCount*1.0/TotalCount")
	
		# get data
		edge_expr_data_rand <- dbGetQuery(con, "
		SELECT * FROM ppi_edge_expr_rand
		ORDER BY ExpressedFraction")
		
		# append new results to total result
		result <- c(result, edge_expr_data_rand$ExpressedFraction)
		
		print("Done with:")
		print(i)
	}
	
	# return all data
	return(result)
}




edge_expr_data <- dbGetQuery(con, "
	SELECT * FROM ppi_edge_expr
	ORDER BY ExpressedFraction")

# Error in sqliteExecStatement(con, statement, bind.data) : 
#   RS-DBI driver: (expired SQLiteConnection)

#edge_expr_frac_rand <- rand_edge_expr_frac(con, 1, TRUE)
edge_expr_frac_glob_rand <- rand_edge_expr_frac(con, 10, FALSE)

dbDisconnect(con)



#plot(density(data$ExpressedFraction))

#h_rand <- hist(edge_expr_frac_rand, breaks=50, plot=FALSE)
#h_real <- hist(edge_expr_data$ExpressedFraction, breaks=50, plot=FALSE)
# 

#h$counts <- cumsum(h$counts)
#h$density <- cumsum(h$density)
#plot(h_rand, col="lightblue", xlab="Edge expression", main="Histrogram of edge expression", xlim=c(0,1))
#lines(h_real, col="orange")

# load ggplot2
library(ggplot2)

# choose bin width
binwidth <- 0.02

#fig = ggplot(edge_expr_data_rand, aes(x=ExpressedFraction))
# 
fig = ggplot(xlim=c(0,1))
#fig = fig + stat_bin(data=as.data.frame(edge_expr_frac_rand), binwidth=binwidth, fill="blue", alpha=0.5, aes(x=edge_expr_frac_rand, y=5*..count../sum(..count..)), position="identity")
fig = fig + stat_bin(data=as.data.frame(edge_expr_frac_glob_rand), binwidth=binwidth, alpha=0.5, aes(x=edge_expr_frac_glob_rand, y=5*..count../sum(..count..), fill="Random Permutations"), position="identity")
fig = fig + stat_bin(data=edge_expr_data, binwidth=binwidth, alpha=0.5, aes(x=ExpressedFraction, y=5*..count../sum(..count..), fill="Actual Data"), position="identity")
fig = fig + ylab("Fraction")
fig = fig + xlab("Edge Expression")
fig = fig + labs(title="Histogram of Edge Expression")
fig = fig + scale_fill_manual(name="Edge Expression for:",values=c("orange","blue"))
fig = fig + theme(legend.position=c(1,1),legend.justification=c(1,1))
#actually plot:
fig







