# tries to analyse the edge expression levels (how specific edges are)
# based on the data generated by pappi/sql/edge_expression.sql
# Author: flick
###############################################################################

# load utils
source("utils.R", chdir=TRUE)

# load sql config and get connection
source("sql_config.R", chdir=TRUE)
con <- get_sql_conn()


expr_data <- dbGetQuery(con, "
	SELECT Gene, 
		SUM(Expressed) as CountExpressed,
		count() as CountTotal,
		SUM(Expressed)*1.0/count() as ExpressedFraction
	FROM hpa_tissue_expr
	GROUP BY Gene")


dbDisconnect(con)



#plot(density(data$ExpressedFraction))

#h_rand <- hist(edge_expr_frac_rand, breaks=50, plot=FALSE)
#h_real <- hist(edge_expr_data$ExpressedFraction, breaks=50, plot=FALSE)
# 

#h$counts <- cumsum(h$counts)
#h$density <- cumsum(h$density)
#plot(h_rand, col="lightblue", xlab="Edge expression", main="Histrogram of edge expression", xlim=c(0,1))
#lines(h_real, col="orange")

# load ggplot2
library(ggplot2)

# choose bin width
binwidth <- 0.02

#fig = ggplot(edge_expr_data_rand, aes(x=ExpressedFraction))
# 
fig = ggplot(xlim=c(0,1))
fig = fig + stat_bin(data=expr_data, binwidth=binwidth, alpha=0.5, aes(x=ExpressedFraction, y=5*..count../sum(..count..), fill="Actual Data"), position="identity")
#fig = fig + stat_ecdf(data=expr_data,aes(x=ExpressedFraction))
fig = fig + ylab("Fraction")
fig = fig + xlab("Fraction of cell types the edge is expressed")
fig = fig + labs(title="Histogram of Protein Expression")
fig = fig + scale_fill_manual(name="Protein Expression",values=c("blue"))
fig = fig + theme(legend.position=c(1,1),legend.justification=c(1,1))
#actually plot:
fig







