# tries to analyse the edge expression levels (how specific edges are)
# based on the data generated by pappi/sql/edge_expression.sql
# Author: flick
###############################################################################

# load utils
source("utils.R", chdir=TRUE)

# load sql config and get connection
source("sql_config.R", chdir=TRUE)
con <- get_sql_conn("mmc_edge_expr.sqlite")


rand_edge_expr_frac <- function(con, iterations=1, per_gene_permute=FALSE)
{

	# initiate empty result
	result <- c()
	
	# iterate random permutations and edge expression calculation
	for (k in 1:iterations)
	{
		# get tissue/cell.type expression data
		expr_data <- dbGetQuery(con, "
			SELECT * FROM hpa_tissue_expr
			ORDER BY Gene")
		
		if (per_gene_permute)
		{
			#for (gene in unique(expr_data$Gene))
			#{
			#	expr_data[which(expr_data$Gene == gene),"Expressed"] <- sample(expr_data[which(expr_data$Gene == gene),"Expressed"])
			#}
			i <- 1
			j <- 2
			while (i <= length(expr_data$Gene))
			{
				while (expr_data$Gene[i] == expr_data$Gene[j] && j < length(expr_data$Gene))
				{
					j <- j + 1
				}
				
				if (expr_data$Gene[i] == expr_data$Gene[j] && j == length(expr_data$Gene))
				{
					j <- j + 1
				}
				
				expr_data[i:(j-1),"Expressed"] <- sample(expr_data[i:(j-1),"Expressed"])
				
				i <- j
				j <- i + 1
			}
			
		}
		else
		{
			# permutate expression
			expr_data$Expressed <- sample(expr_data$Expressed)
		}
		
		# write new table
		dbWriteTable(con, "hpa_tissue_expr_rand", expr_data, overwrite=TRUE)

		# intersect with edges to get edge-expression
		dbSendQuery(con, "DROP TABLE IF EXISTS ppi_edge_expr_rand")
		dbSendQuery(con, "
		CREATE TABLE ppi_edge_expr_rand AS
		SELECT
			a.Gene1,
			a.Gene2,
			SUM(CASE
				WHEN
					b.Expressed = 1 
					AND c.Expressed = 1
				THEN 1 
				ELSE 0 
				END) AS ExpressedCount,
			count() AS TotalCount
		FROM ppi_hgnc AS a
		INNER JOIN hpa_tissue_expr_rand AS b
			ON a.Gene1 = b.Gene
		INNER JOIN hpa_tissue_expr_rand AS c
			ON a.Gene2 = c.Gene
			AND b.Tissue = c.Tissue
			AND b.[Cell_Type] = c.[Cell_Type]
		GROUP BY
			a.Gene1, a.Gene2
		")
		
		dbSendQuery(con, "ALTER TABLE ppi_edge_expr_rand ADD ExpressedFraction float")
		dbSendQuery(con, "UPDATE ppi_edge_expr_rand
		SET ExpressedFraction = ExpressedCount*1.0/TotalCount")
	
		# get data
		edge_expr_data_rand <- dbGetQuery(con, "
		SELECT * FROM ppi_edge_expr_rand
		ORDER BY ExpressedFraction")
		
		# append new results to total result
		result <- c(result, edge_expr_data_rand$ExpressedFraction)
		
		print("Done with:")
		print(k)
	}
	
	# return all data
	return(result)
}


dbSendQuery(con,"DROP TABLE IF EXISTS edge_expr_rand_perm_results")
dbSendQuery(con,"CREATE TABLE edge_expr_rand_perm_results ('Experiment' int, 'Results' float)")



batch_size <- 200
for (batch_nr in 1:batch_size)
{
	edge_expr_frac_rand <- rand_edge_expr_frac(con, 1, TRUE)
	new_data <- data.frame(Experiment=c(batch_nr),Results=edge_expr_frac_rand)
	
	dbWriteTable(con, "edge_expr_rand_perm_results", new_data[,c("Experiment","Results")], row.names=FALSE, append=TRUE)
}


dbDisconnect(con)









